### PR TITLE
Implemented PyCaret and enhanced accuracy using multiple regression models at a time

### LINKED ISSUE #2: Enhance accuracy by using multiple regression models at a time
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hey, am a fellow contributor of GSSOC'23 and would like to implement pycaret module to test and deploy about 25 regression models and select the best model with above 90% accuracy. AutoML is advanced machine learning technique and with appropriate tuning and ensembling, we would get much better insights on drug reviews by different patients.

### Screenshots

image

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by manishkumar00208**
# Fixes Issue🛠️

Closes #2 

# Description👨‍💻 

Dependencies: PyCaret Module, pip install pycaret

I've implemented pycaret module on the given datasets to test and deploy about 25 regression models and select the best model with above 90% accuracy. AutoML is advanced machine learning technique and with appropriate tuning and ensembling, we would get much better insights on drug reviews by different patients.

Target: rating

# Type of change📄

- [✅] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I ran through my code using the provided Datasets (drugComTest and drugComTrain) and the output is absolutely working fine as per the expectations. Moreover, I've performed testing my code in the existing environment i.e., Preprocessed data.

# Checklist✅ 

- [✅] My code follows the style guidelines of this project
- [✅] I have performed a self-review of my own code
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have added demonstration in the photos attached
- [✅] I am an Open Source Contributor

# Screenshots/GIF📷
modela_1
models
These are a few screenshots of Regression Models as a result of Pycaret implementation on Drug Datasets. I can also provide you the screenshots of the plots and Analysis of the best regression model with best accuracy.

### CODE REVIEW

**Comment by manishkumar00208** [comment]
@Rakesh9100 Please review this PR and merge it to the main repo.

**Review by abhisheks008 — APPROVED** [review]
Looks good to me.
@manishkumar00208

**Comment by Rakesh9100** [comment]
Pls provide the screenshots of the best model with its accuracy and also its plots @manishkumar00208

**Comment by manishkumar00208** [comment]
@Rakesh9100 sure, Give me sometime to run all the models and let me get it for you!

**Comment by manishkumar00208** [comment]
@Rakesh9100 
Here are the plots of best model:
Screenshot 2023-07-02 221441
Screenshot 2023-07-02 221511
Best Model with it's accuracy:
Screenshot 2023-07-02 221618

I have compared all the models but I forgot to take it's screenshot. It is taking very long time to execute compare_models, due to my end semester schedule I'm unable to do it again now. But I'm sure that it is working fine, if you want to you can do it....!

**Comment by Rakesh9100** [comment]
No issues. I can see that the code is OK and also these screenshots are enough to determine.

LGTM!! Congrats on getting your PR merged to this repo 🎉🎉 @manishkumar00208

**Pull request merged**
