### PR TITLE
Added the Arima model

### LINKED ISSUE #83: Add the Arima model
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hii @Rakesh9100 I want to add these model in your dataset please assign this to me asap...
thank you

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by ayushrathore111**
Closes #83 

Implemented the Arima model in the drug dataset

# Description👨‍💻 

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

The model is implemented in vscode via clonning the main directory and before commiting changes all the results have verified and tested..

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Here are the results:
ml contributions 2
ml contributions3
ml_contributions1
Screenshot (257)
Screenshot (259)

### CODE REVIEW

**Comment by Rakesh9100** [comment]
LGTM!! Will merge but just one thing that haven't you worked on SARIMA model as mentioned in the issue @ayushrathore111

**Comment by ayushrathore111** [comment]
After merging this i can open a pull request for that also.

**Comment by Rakesh9100** [comment]
Merged!! Congrats on getting your PR merged to this repo @ayushrathore111

**Comment by Rakesh9100** [comment]
Approved!! Congrats on getting your PR merged to this repo 🎉 @ayushrathore111

**Pull request merged**
