### PR TITLE
Added Logistic Regression model with GridSearchCV

### LINKED ISSUE #1: Add GridSearchCV for identifying best model
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

As being a gssoc contributor i would like to contribute to this repo, by adding GridSearchCV to the code base that would help us to identify the best model among the available models

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by karthikbhandary2**
# Fixes Issue🛠️

Closes #1 

# Description👨‍💻 

I ran the existing models in the notebook with GridSearchCV and I found the best model which worked with GridSearch. Logistic regression was the only model which gave better results than the existing ones.
# Type of change📄

- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I ran the notebook in Azure Machine Learning console by using Azure notebook.

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
gs_logi_plot 1
gs_logi_plot 2

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls do resolve the conflics and also run `black main.py` and then commit to pass the lint workflow @karthikbhandary2

**Comment by karthikbhandary2** [comment]
ok @Rakesh9100

**Comment by karthikbhandary2** [comment]
Hey, @Rakesh9100 I have done the changes and now everything is good to go. Please check and merge.

**Comment by Rakesh9100** [comment]
LGTM!! Merged 🎉

**Comment by Rakesh9100** [comment]
LGTM!! Merged 🎉 @karthikbhandary2

**Comment by karthikbhandary2** [comment]
Thanks for the merge!

**Pull request merged**
