### PR TITLE
Added the KNN Model

### LINKED ISSUE #11: Add the KNN Model
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Add alternative models such as SVM, KNN etc. and try results

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by karthikbhandary2**
# Fixes Issue🛠️

Closes #11 

# Description👨‍💻 

Added the KNN model to the main.py
# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Its been run on colab
# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
knn plot

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls put the screenshot of KNN confusion matrix and not of Logistic Regression Matrix @karthikbhandary2

**Comment by karthikbhandary2** [comment]
I did a mistake there I did not change the title of the matrix when I ran the code. But it is of the KNN. I can rerun it with the title changed if you want to. (I mean the currently it is fixed but when I took the ss it was like that)

**Comment by Rakesh9100** [comment]
I can understand that matrix plot is ryt but pls put the proper screenshot @karthikbhandary2

**Comment by karthikbhandary2** [comment]
ok @Rakesh9100

**Comment by karthikbhandary2** [comment]
Here is the updated one

image

**Comment by Rakesh9100** [comment]
LGTM!! Merged 🎉 @karthikbhandary2

**Pull request merged**
