### PR TITLE
Modified file with comments

### LINKED ISSUE #123: Modify file with comments
### Description

As a python user, I can feel that main.py does not consist enough number of comments so that a beginner can understand the codebase easily. Need to add comments properly to make it a beginner-friendly project. Please assign me this issue so I can work on it @Rakesh9100 

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Rancho2002**
# Fixes Issue🛠️

Closes #123 

# Description👨‍💻 

Added more relevant comments so that a beginner can understand the codebase easily.

# Type of change📄
Readibility that mean main.py documentated

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅
It has been tested after committed and pushed successfully

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
image
View more comments by clicking on<b> files changed</b>

### CODE REVIEW

**Comment by Rancho2002** [comment]
Pls have a look @Rakesh9100

**Comment by Rakesh9100** [comment]
Pls run `black main.py` and then commit the new indentation changes to pass the lint workflow @Rancho2002

**Comment by Rancho2002** [comment]
pls check now @Rakesh9100 , I have run the following command as you told

**Comment by Rakesh9100** [comment]
Pls commit the new changes after running the command @Rancho2002

**Comment by Rancho2002** [comment]
I made commit then create pull request, pls tell what to do now? @Rakesh9100

**Comment by Rancho2002** [comment]
Screenshot_2023-06-27-19-31-49-54_40deb401b9ffe8e1df2f1cc5ba480b12
You can check the recent commit 35 min ago, it's made after running black main.py

**Comment by Rakesh9100** [comment]
Yes, I can see the commits but the last commit is not made by you. It is the commit made after you pulled the latest code changes. You have to just `black main.py` on your terminal, there will be some changes, track them using `git status` then `git add .` and then `git commit -m "Write your commit msg"` in this same PR @Rancho2002

**Comment by Rancho2002** [comment]
pls check now @Rakesh9100

**Comment by Rakesh9100** [comment]
LGTM!! Congrats on getting your PR merged to this repo 🎉🎉 @Rancho2002

**Pull request merged**
