### PR TITLE
Added Drug Review Sentiment Classification using DistilBERT Transformer Model

### LINKED ISSUE #80: Add Drug Review Sentiment Classification using DistilBERT Transformer Model
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

The project is about building a machine-learning model to classify drug reviews as either positive or negative. Transformers are a type of neural network that are well-suited for natural language processing tasks, such as text classification.

To apply Transformers to this project, I would first need to train a transformer model on a dataset of drug reviews. The dataset should include both positive and negative reviews. Once the model is trained, I can use it to classify new drug reviews.

Once the model is trained, I can use it to classify new drug reviews. To do this, I would simply input the review text into the model and it would output a prediction of whether the review is positive or negative.

Here are some of the benefits of using Transformers for this project:

Transformers are able to learn long-range dependencies in text, which is important for tasks such as text classification.
Transformers are able to parallelize training, which can significantly reduce the amount of time it takes to train a model.
Transformers are able to generalize well to new data, which is important for tasks such as drug review classification.

Here are some of the challenges of using Transformers for this project:

Transformers can be computationally expensive to train and deploy.
Transformers require a large amount of data to train.
Transformers can be difficult to debug.

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by Nabanita29**
# Fixes Issue🛠️
Closes #80 

# Description👨‍💻 

This pull request implements a machine learning model for classifying drug reviews as either positive or negative using transformers, specifically the DistilBERT model.

Proposed Changes:

1. Used the tsv file to train and use the transformer model for drug review classification. A point to be noted is transformers like DistilBERT have their own initial embedding layers so the original text data was used , not the Word2Vec embeddings. 
2. Included the required data preprocessing steps, such as reading the dataset, tokenization, label modification, and data splitting.
3. Implement the model training and evaluation pipeline(Ratings above the 5 was considered positive), including the necessary training arguments and the model trainer.
4. Saved the trained model and tokenizer for later use. 
5. Tested the model with new reviews and provide sample predictions.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

After the model training and evaluation, I've added a step where we test how the model classifies new, unseen reviews. This is an essential step to understand the model's performance in real-world scenarios.

# Checklist✅ 
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I am an Open Source Contributor (GSSOC'23)

### CODE REVIEW

**Comment by Nabanita29** [comment]
Sir please let me know if I can improve on this further or modify something!

**Comment by Rakesh9100** [comment]
Pls provide the new unseen data results screenshots @Nabanita29

**Comment by Nabanita29** [comment]
Sir the new unseen data screenshots along with the evaluation metrics of the model I implemented are listed : 

image
image
image
image

**Comment by Nabanita29** [comment]
Sir please let me know if there is anything else I can improve so the PR can be counted to Gssoc! Thank you

**Comment by Rakesh9100** [comment]
LGTM!! Pls just change the PR title similar to the work you have done @Nabanita29

**Comment by Nabanita29** [comment]
done sir

**Comment by Rakesh9100** [comment]
Nice work, Merged!! Congrats on getting your PR merged to this repo 🥳🎉 @Nabanita29

**Pull request merged**
