### PR TITLE
Added black linter workflow

### LINKED ISSUE #14: Add black linter workflow
Add a suitable linter to ensure proper linting of the code. As a project with multiple users contributing to it, it is essential to maintain a proper linting style to ensure better code readability by users. An excellent way to do this is by automatic linting checks using GitHub actions.

I would like to work on this project as a part of GSSoC 23. Please assign this issue to me.

### PR DESCRIPTION
**Pull request by metabiswadeep**
# Fixes Issue🛠️

Closes #14 

# Description👨‍💻 

Added the black linter to ensure uniform linting for the entire codebase.

# Type of change📄

[l] New feature (non-breaking change which adds functionality)

# How this has been tested✅

Ran the black linter on the repo locally, which suggested the same changes.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

### CODE REVIEW

**Comment by Rakesh9100** [comment]
If you ran it locally, has it passed all the checks in the `main.py` file? Pls provide the screenshot.

**Comment by Rakesh9100** [comment]
If you ran it locally or in your forked repo, has it passed all the checks in the `main.py` file? Pls provide the screenshot.

**Comment by metabiswadeep** [comment]
It has not passed all the tests on main.py. It has suggested the following changes, which is in accordance to black's style rules (for eg. ' ' should be written as " " according to black). The tests can be easily passed by running black on the local pc which can reformat the file in accordance with black's linting rules as can be seen here.
Screenshot 2023-05-27 202349

If it would be preferable for me to reformat the files in this PR itself, please inform me accordingly.

The following is the output from the black Github action
```--- /home/runner/work/ML-Project-Drug-Review-Dataset/ML-Project-Drug-Review-Dataset/main.py	20[23](https://github.com/metabiswadeep/ML-Project-Drug-Review-Dataset/actions/runs/5098468464/jobs/9165626623#step:3:25)-05-27 11:05:11.708787 +0000
would reformat /home/runner/work/ML-Project-Drug-Review-Dataset/ML-Project-Drug-Review-Dataset/main.py
+++ /home/runner/work/ML-Project-Drug-Review-Dataset/ML-Project-Drug-Review-Dataset/main.py	2023-05-27 11:05:17.180890 +0000
@@ -6,199 +6,[25](https://github.com/metabiswadeep/ML-Project-Drug-Review-Dataset/actions/runs/5098468464/jobs/9165626623#step:3:27)2 @@
 from sklearn.feature_extraction.text import TfidfVectorizer
 from sklearn.preprocessing import LabelEncoder
 from sklearn.linear_model import LinearRegression, LogisticRegression
 from sklearn.neural_network import MLPClassifier
 from sklearn.tree import DecisionTreeClassifier
-from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, confusion_matrix, ConfusionMatrixDisplay 
+from sklearn.metrics import (
+    mean_squared_error,
+    r2_score,
+    accuracy_score,
+    confusion_matrix,
+    ConfusionMatrixDisplay,
+)
 import seaborn as sns
 import matplotlib.pyplot as plt
 
 from keras.models import Sequential
 from keras.layers import Dense, LSTM, Embedding
 
 ## Reading the data
-dtypes = { 'Unnamed: 0': 'int32', 'drugName': 'category', 'condition': 'category', 'review': 'category', 'rating': 'float16', 'date': 'category', 'usefulCount': 'int16' }
-train_df = pd.read_csv('datasets/drugsComTrain_raw.tsv', sep='\t', dtype=dtypes)
+dtypes = {
+    "Unnamed: 0": "int32",
+    "drugName": "category",
+    "condition": "category",
+    "review": "category",
+    "rating": "float16",
+    "date": "category",
+    "usefulCount": "int16",
+}
+train_df = pd.read_csv("datasets/drugsComTrain_raw.tsv", sep="\t", dtype=dtypes)
 # Randomly selecting 80% of the data from the training dataset
 train_df = train_df.sample(frac=0.8, random_state=42)
-test_df = pd.read_csv('datasets/drugsComTest_raw.tsv', sep='\t', dtype=dtypes)
+test_df = pd.read_csv("datasets/drugsComTest_raw.tsv", sep="\t", dtype=dtypes)
 
 ## Converting date column to datetime format
-train_df['date'], test_df['date'] = pd.to_datetime(train_df['date'], format='%B %d, %Y'), pd.to_datetime(test_df['date'], format='%B %d, %Y')
+train_df["date"], test_df["date"] = pd.to_datetime(
+    train_df["date"], format="%B %d, %Y"
+), pd.to_datetime(test_df["date"], format="%B %d, %Y")
 
 ## Extracting day, month, and year into separate columns
 for df in [train_df, test_df]:
-    df['day'] = df['date'].dt.day.astype('int8')
-    df['month'] = df['date'].dt.month.astype('int8')
-    df['year'] = df['date'].dt.year.astype('int16')
+    df["day"] = df["date"].dt.day.astype("int8")
+    df["month"] = df["date"].dt.month.astype("int8")
+    df["year"] = df["date"].dt.year.astype("int16")
 
 ## Suppressing MarkupResemblesLocatorWarning, FutureWarning and ConvergenceWarning
-warnings.filterwarnings('ignore', category=MarkupResemblesLocatorWarning)
-warnings.simplefilter(action='ignore', category=FutureWarning)
+warnings.filterwarnings("ignore", category=MarkupResemblesLocatorWarning)
+warnings.simplefilter(action="ignore", category=FutureWarning)
 warnings.filterwarnings("ignore", category=ConvergenceWarning)
+
 

Oh no! 💥 💔 💥
1 file would be reformatted.
 ## Defining function to decode HTML-encoded characters
 def decode_html(text):
-    decoded_text = BeautifulSoup(text, 'html.parser').get_text()
+    decoded_text = BeautifulSoup(text, "html.parser").get_text()
     return decoded_text
 
+
 ## Applying the function to the review column
-train_df['review'], test_df['review'] = train_df['review'].apply(decode_html), test_df['review'].apply(decode_html)
+train_df["review"], test_df["review"] = train_df["review"].apply(decode_html), test_df[
+    "review"
+].apply(decode_html)
 
 ## Dropped the original date column and removed the useless column
-train_df, test_df = [df.drop('date', axis=1).drop(df.columns[0], axis=1) for df in (train_df, test_df)]
+train_df, test_df = [
+    df.drop("date", axis=1).drop(df.columns[0], axis=1) for df in (train_df, test_df)
+]
 
 ## Handling the missing values
-train_imp, test_imp = [pd.DataFrame(SimpleImputer(strategy='most_frequent').fit_transform(df)) for df in (train_df, test_df)]
+train_imp, test_imp = [
+    pd.DataFrame(SimpleImputer(strategy="most_frequent").fit_transform(df))
+    for df in (train_df, test_df)
+]
 
 ## Assigning old column names
-train_imp.columns = ['drugName', 'condition', 'review', 'rating', 'usefulCount', 'day', 'month', 'year']
-test_imp.columns = ['drugName', 'condition', 'review', 'rating', 'usefulCount', 'day', 'month', 'year']
+train_imp.columns = [
+    "drugName",
+    "condition",
+    "review",
+    "rating",
+    "usefulCount",
+    "day",
+    "month",
+    "year",
+]
+test_imp.columns = [
+    "drugName",
+    "condition",
+    "review",
+    "rating",
+    "usefulCount",
+    "day",
+    "month",
+    "year",
+]
 
 ## Converting the text in the review column to numerical data
-vectorizer = TfidfVectorizer(stop_words='english', max_features=3000)
-train_reviews = vectorizer.fit_transform(train_imp['review'])
-test_reviews = vectorizer.transform(test_imp['review'])
+vectorizer = TfidfVectorizer(stop_words="english", max_features=3000)
+train_reviews = vectorizer.fit_transform(train_imp["review"])
+test_reviews = vectorizer.transform(test_imp["review"])
 
 ## Replacing the review column with the numerical data
-train_imp.drop('review', axis=1, inplace=True)
-test_imp.drop('review', axis=1, inplace=True)
+train_imp.drop("review", axis=1, inplace=True)
+test_imp.drop("review", axis=1, inplace=True)
 train_imp = pd.concat([train_imp, pd.DataFrame(train_reviews.toarray())], axis=1)
 test_imp = pd.concat([test_imp, pd.DataFrame(test_reviews.toarray())], axis=1)
 
 ## Encoding the categorical columns
 for i in ["drugName", "condition"]:
     train_imp[i] = LabelEncoder().fit_transform(train_imp[i])
     test_imp[i] = LabelEncoder().fit_transform(test_imp[i])
 
 ## Converting the data types of columns to reduce the memory usage
-train_imp, test_imp = train_imp.astype('float16'), test_imp.astype('float16')
-train_imp[['drugName', 'condition', 'usefulCount', 'year']] = train_imp[['drugName', 'condition', 'usefulCount', 'year']].astype('int16')
-test_imp[['drugName', 'condition', 'usefulCount', 'year']] = test_imp[['drugName', 'condition', 'usefulCount', 'year']].astype('int16')
-train_imp[['rating']] = train_imp[['rating']].astype('float16')
-test_imp[['rating']] = test_imp[['rating']].astype('float16')
-train_imp[['day', 'month']] = train_imp[['day', 'month']].astype('int8')
-test_imp[['day', 'month']] = test_imp[['day', 'month']].astype('int8')
-
-#print(train_imp.iloc[:,:15].dtypes)
-#print(test_imp.iloc[:,:15].dtypes)
+train_imp, test_imp = train_imp.astype("float16"), test_imp.astype("float16")
+train_imp[["drugName", "condition", "usefulCount", "year"]] = train_imp[
+    ["drugName", "condition", "usefulCount", "year"]
+].astype("int16")
+test_imp[["drugName", "condition", "usefulCount", "year"]] = test_imp[
+    ["drugName", "condition", "usefulCount", "year"]
+].astype("int16")
+train_imp[["rating"]] = train_imp[["rating"]].astype("float16")
+test_imp[["rating"]] = test_imp[["rating"]].astype("float16")
+train_imp[["day", "month"]] = train_imp[["day", "month"]].astype("int8")
+test_imp[["day", "month"]] = test_imp[["day", "month"]].astype("int8")
+
+# print(train_imp.iloc[:,:15].dtypes)
+# print(test_imp.iloc[:,:15].dtypes)
 
 ## Splitting the train and test datasets into feature variables
-X_train, Y_train = train_imp.drop('rating', axis=1), train_imp['rating']
-X_test, Y_test = test_imp.drop('rating', axis=1), test_imp['rating']
+X_train, Y_train = train_imp.drop("rating", axis=1), train_imp["rating"]
+X_test, Y_test = test_imp.drop("rating", axis=1), test_imp["rating"]
 
 X_train.columns = X_train.columns.astype(str)
 X_test.columns = X_test.columns.astype(str)
 
 ##### LinearRegression regression algorithm #####
 
-linear=LinearRegression()
+linear = LinearRegression()
 linear.fit(X_train, Y_train)
-line_train=linear.predict(X_train)
-line_test=linear.predict(X_test)
+line_train = linear.predict(X_train)
+line_test = linear.predict(X_test)
 
 print("Linear Regression Metrics:")
 print("MSE for training: ", mean_squared_error(Y_train, line_train))
 print("MSE for testing: ", mean_squared_error(Y_test, line_test))
 print("R2 score for training: ", r2_score(Y_train, line_train))
 print("R2 score for testing: ", r2_score(Y_test, line_test))
 
 # Plotting the scatter plot of predicted vs actual values for training data
 plt.scatter(Y_train, line_train)
-plt.xlabel('Actual Ratings')
-plt.ylabel('Predicted Ratings')
-plt.title('Linear Regression - Training Data Scatter Plot')
+plt.xlabel("Actual Ratings")
+plt.ylabel("Predicted Ratings")
+plt.title("Linear Regression - Training Data Scatter Plot")
 plt.show()
 
 # Plotting the scatter plot of predicted vs actual values for testing data
 plt.scatter(Y_test, line_test)
-plt.xlabel('Actual Ratings')
-plt.ylabel('Predicted Ratings')
-plt.title('Linear Regression - Testing Data Scatter Plot')
+plt.xlabel("Actual Ratings")
+plt.ylabel("Predicted Ratings")
+plt.title("Linear Regression - Testing Data Scatter Plot")
 plt.show()
 
 # Plotting the scatter plot of predicted vs true values for both training and testing sets
-plt.figure(figsize=(8,6))
-plt.scatter(Y_train, line_train, alpha=0.3, label='Training')
-plt.scatter(Y_test, line_test, alpha=0.3, label='Testing')
-plt.plot([0,10], [0,10], linestyle='--', color='k', label='Perfect prediction')
-plt.xlabel('True Ratings')
-plt.ylabel('Predicted Ratings')
-plt.title('Linear regression - Training and Testing Sets Scatter Plot')
+plt.figure(figsize=(8, 6))
+plt.scatter(Y_train, line_train, alpha=0.3, label="Training")
+plt.scatter(Y_test, line_test, alpha=0.3, label="Testing")
+plt.plot([0, 10], [0, 10], linestyle="--", color="k", label="Perfect prediction")
+plt.xlabel("True Ratings")
+plt.ylabel("Predicted Ratings")
+plt.title("Linear regression - Training and Testing Sets Scatter Plot")
 plt.legend()
 plt.show()
 
 # Plotting the residual plot for testing data
-plt.scatter(line_test, line_test - Y_test, c='g', s=40, alpha=0.5)
+plt.scatter(line_test, line_test - Y_test, c="g", s=40, alpha=0.5)
 plt.hlines(y=0, xmin=0, xmax=10)
-plt.xlabel('Predicted Ratings')
-plt.ylabel('Residuals')
-plt.title('Linear Regression - Testing Data Residual Plot')
+plt.xlabel("Predicted Ratings")
+plt.ylabel("Residuals")
+plt.title("Linear Regression - Testing Data Residual Plot")
 plt.show()
 
 ##### LogisticRegression classification algorithm #####
 
-logi=LogisticRegression()
+logi = LogisticRegression()
 logi.fit(X_train, Y_train)
-logi_train=logi.predict(X_train)
-logi_test=logi.predict(X_test)
+logi_train = logi.predict(X_train)
+logi_test = logi.predict(X_test)
 
 train_accuracy = accuracy_score(logi_train, Y_train)
 test_accuracy = accuracy_score(logi_test, Y_test)
 print("\nLogistic Regression Metrics:")
 print("Accuracy for training: ", train_accuracy)
 print("Accuracy for testing: ", test_accuracy)
 
 # Plotting the accuracy plot
-plt.plot(['Training', 'Testing'], [train_accuracy, test_accuracy], marker='o')
-plt.title('Logistic Regression Accuracy')
-plt.xlabel('Dataset')
-plt.ylabel('Accuracy')
+plt.plot(["Training", "Testing"], [train_accuracy, test_accuracy], marker="o")
+plt.title("Logistic Regression Accuracy")
+plt.xlabel("Dataset")
+plt.ylabel("Accuracy")
 plt.show()
 
 # Plotting the confusion matrix
 cm = confusion_matrix(Y_test, logi_test, labels=logi.classes_)
 ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=logi.classes_).plot()
-plt.title('Logistic Regression Confusion Matrix')
+plt.title("Logistic Regression Confusion Matrix")
 plt.show()
 
 
 ##### Perceptron Model classification algorithm #####
 
 
-mlpcls = MLPClassifier(hidden_layer_sizes=(30,30),activation="relu",random_state=1,max_iter=300).fit(X_train, Y_train)
-
-mlpcls_train=mlpcls.predict(X_train)
-mlpcls_test=mlpcls.predict(X_test)
+mlpcls = MLPClassifier(
+    hidden_layer_sizes=(30, 30), activation="relu", random_state=1, max_iter=300
+).fit(X_train, Y_train)
+
+mlpcls_train = mlpcls.predict(X_train)
+mlpcls_test = mlpcls.predict(X_test)
 print("\nMulti Layer Perceptron Metrics:")
-print("Accuracy for training ",accuracy_score(mlpcls_train,Y_train))
-print("Accuracy for testing ",accuracy_score(mlpcls_test,Y_test))
+print("Accuracy for training ", accuracy_score(mlpcls_train, Y_train))
+print("Accuracy for testing ", accuracy_score(mlpcls_test, Y_test))
 
 
 # Plotting the scatter plot of actual vs predicted values
-plt.scatter(Y_test, mlpcls_test, color='blue', label='Predicted Ratings')
-plt.scatter(Y_test, Y_test, color='red', label='Actual Ratings')
-plt.title('Scatter Plot -- Actual vs Predicted values for Multi Layer Perceptron Model')
-plt.xlabel('Actual Ratings')
-plt.ylabel('Predicted Ratings')
+plt.scatter(Y_test, mlpcls_test, color="blue", label="Predicted Ratings")
+plt.scatter(Y_test, Y_test, color="red", label="Actual Ratings")
+plt.title("Scatter Plot -- Actual vs Predicted values for Multi Layer Perceptron Model")
+plt.xlabel("Actual Ratings")
+plt.ylabel("Predicted Ratings")
 plt.legend()
 plt.show()
 
 # Plotting the step plot of accuracy
-plt.step([0, 1], [accuracy_score(mlpcls_train, Y_train), accuracy_score(mlpcls_test, Y_test)], where='post')
-plt.title('Step Plot -- Accuracy for Multi Layer Perceptron Model')
-plt.xticks([0, 1], ['Training', 'Testing'])
-plt.ylabel('Accuracy')
+plt.step(
+    [0, 1],
+    [accuracy_score(mlpcls_train, Y_train), accuracy_score(mlpcls_test, Y_test)],
+    where="post",
+)
+plt.title("Step Plot -- Accuracy for Multi Layer Perceptron Model")
+plt.xticks([0, 1], ["Training", "Testing"])
+plt.ylabel("Accuracy")
 plt.ylim([0, 1])
 plt.show()
 
 # Plotting the Confusion matrix
 cm = confusion_matrix(Y_test, mlpcls_test)
-sns.heatmap(cm, annot=True, cmap='Blues')
-plt.title('MultilayerPerceptron - Confusion Matrix')
-plt.xlabel('Predicted')
-plt.ylabel('True')
+sns.heatmap(cm, annot=True, cmap="Blues")
+plt.title("MultilayerPerceptron - Confusion Matrix")
+plt.xlabel("Predicted")
+plt.ylabel("True")
 plt.show()
 
 ##### Decision Tree Classifier algorithm #####
 
 dt = DecisionTreeClassifier(criterion="entropy", max_depth=5)
@@ -206,38 +259,40 @@
 train_acc = []
 test_acc = []
 print("\nDecisionTreeClassifier Metrics:\n")
 for i in range(1, 11):
     dt.fit(X_train, Y_train)
-    train_pred=dt.predict(X_train)
-    test_pred=dt.predict(X_test)
+    train_pred = dt.predict(X_train)
+    test_pred = dt.predict(X_test)
     train_acc.append(accuracy_score(train_pred, Y_train))
     test_acc.append(accuracy_score(test_pred, Y_test))
     print(f"Epoch {i} Training Accuracy: {train_acc[-1]}")
     print(f"Epoch {i} Testing Accuracy: {test_acc[-1]}")
 
 # Plotting accuracy vs epoch
 epochs = range(1, 11)
-plt.plot(epochs, train_acc, 'bo-', label='Training Accuracy')
-plt.plot(epochs, test_acc, 'go-', label='Testing Accuracy')
-plt.title('Decision Tree Classifier Accuracy')
-plt.xlabel('Epochs')
-plt.ylabel('Accuracy')
+plt.plot(epochs, train_acc, "bo-", label="Training Accuracy")
+plt.plot(epochs, test_acc, "go-", label="Testing Accuracy")
+plt.title("Decision Tree Classifier Accuracy")
+plt.xlabel("Epochs")
+plt.ylabel("Accuracy")
 plt.legend()
 plt.show()
 
 # Plotting the scatter plot of actual vs predicted values
 plt.scatter(Y_test, test_pred, alpha=0.3)
-plt.xlabel('Actual Rating')
-plt.ylabel('Predicted Rating')
-plt.title('Decision Tree Classifier - Testing Data Scatter Plot')
+plt.xlabel("Actual Rating")
+plt.ylabel("Predicted Rating")
+plt.title("Decision Tree Classifier - Testing Data Scatter Plot")
 plt.show()
 
 # Plotting the confusion matrix
 cm = confusion_matrix(Y_test, test_pred, labels=dt.classes_)
-ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=logi.classes_).plot(cmap='Blues')
-plt.title('Decision Tree Classifier - Confusion Matrix')
+ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=logi.classes_).plot(
+    cmap="Blues"
+)
+plt.title("Decision Tree Classifier - Confusion Matrix")
 plt.show()
 
 
 ##### Long Short-Term Memory algorithm #####
 
@@ -250,18 +305,18 @@
 X_train = X_train.values.reshape(129038, 3006, 1)
 
 # Reshape the y_train data
 Y_train = Y_train.values.reshape(129038, 1)
 
-#Reshape the Y_test data
-Y_test = Y_test.values.reshape(53766,1)
-
-#Reshape the X_test data
-X_test = X_test.values.reshape(53766,3006,1)
+# Reshape the Y_test data
+Y_test = Y_test.values.reshape(53766, 1)
+
+# Reshape the X_test data
+X_test = X_test.values.reshape(53766, 3006, 1)
 
 # Compile the model
-model.compile(loss='mse', optimizer='adam')
+model.compile(loss="mse", optimizer="adam")
 
 # Fit the model
 model.fit(X_train, Y_train, epochs=10)
 
 # Evaluate the model
@@ -[28](https://github.com/metabiswadeep/ML-Project-Drug-Review-Dataset/actions/runs/5098468464/jobs/9165626623#step:3:30)8,13 +343,13 @@
 # Reshape the predictions
 train_predictions = train_predictions.reshape(train_predictions.shape[0])
 
 # Create a scatter plot
 plt.scatter(Y_train, train_predictions)
-plt.xlabel('Actual Values')
-plt.ylabel('Predicted Values')
-plt.title('Scatter Plot: Predicted vs Actual (Training Data)')
+plt.xlabel("Actual Values")
+plt.ylabel("Predicted Values")
+plt.title("Scatter Plot: Predicted vs Actual (Training Data)")
 plt.show()
 
 # Plotting the scatter plot of predicted vs actual values for testing data
 
 # Make predictions on testing data
@@ -[30](https://github.com/metabiswadeep/ML-Project-Drug-Review-Dataset/actions/runs/5098468464/jobs/9165626623#step:3:32)3,9 +[35](https://github.com/metabiswadeep/ML-Project-Drug-Review-Dataset/actions/runs/5098468464/jobs/9165626623#step:3:37)8,9 @@
 # Reshape the predictions
 test_predictions = test_predictions.reshape(test_predictions.shape[0])
 
 # Create a scatter plot
 plt.scatter(Y_test, test_predictions)
-plt.xlabel('Actual Values')
-plt.ylabel('Predicted Values')
-plt.title('Scatter Plot: Predicted vs Actual (Testing Data)')
-plt.show()
\ No newline at end of file
+plt.xlabel("Actual Values")
+plt.ylabel("Predicted Values")
+plt.title("Scatter Plot: Predicted vs Actual (Testing Data)")
+plt.show()```

**Comment by Rakesh9100** [comment]
Okay. It will be good if you include `pip install black` in the yml file or requirements.txt file for the ease. @metabiswadeep

**Comment by metabiswadeep** [comment]
Done @Rakesh9100

**Comment by Rakesh9100** [comment]
Merged @metabiswadeep Congrats on getting your PR merged to this repo under GSSoC23 🎉

**Pull request merged**
