### PR TITLE
Implemented EDA, Data Preprocessing and Oversampling

### PR DESCRIPTION
**Pull request by HarshAggarwal1**
# Fixes Issue🛠️

Closes #31 

# Description👨‍💻 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Provide the screenshots of your every outputs accuracy and plots

**Comment by HarshAggarwal1** [comment]
null_tr
null_t
bocplot
class_imb
class_imb_1

Uploaded all Screenshots including EDA and Oversampling @Rakesh9100

**Comment by Rakesh9100** [comment]
Can you confirm me once that every applied model including yours is running flawlessly after your changes ?

**Comment by HarshAggarwal1** [comment]
Yes, don't worry, every model is running fine.

**Comment by Rakesh9100** [comment]
Good work!! Congrats on getting your PR merged to this repo under GSSoC23 @HarshAggarwal1 Keep Contributing

**Comment by HarshAggarwal1** [comment]
Thanks

**Pull request merged**
