### PR TITLE
Added LSTM Model

### LINKED ISSUE #26: Add LSTM Model
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

Hey Everyone!

Myself Archisman | Contributor GSSOC'23

> Based on the dataset in the repo, I would recommend using a long short-term memory (LSTM) network.

Here are some specific suggestions for using an LSTM network for the project:

1. **Extract features from the text of the review:** The LSTM network can be used to extract features from the text of the review. These features can then be used to train a machine-learning model that can predict the sentiment of the review.

2. **Identify the sentiment of the review:** The LSTM network can be used to identify the sentiment of the review. This can be done by training the LSTM network on a dataset of reviews that have been labeled with the sentiment.

3. **Recommend drugs to users based on the sentiment of the review:** The LSTM network can be used to recommend drugs to users based on the sentiment of the review. This can be done by training the LSTM network on a dataset of reviews that have been labeled with both sentiment and the drug that was recommended to the user.

By following these suggestions, the LSTM network can be used to improve the accuracy and efficiency of the project.

### Screenshots

_No response_

### Code of Conduct

- [x] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by Mochoye**
# Fixes Issue🛠️

Closes #26 

# Description👨‍💻 

I have made significant changes in this pull request by adding an LSTM model to the existing codebase. The LSTM model is a deep learning technique that enhances the performance of the system.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
Output_Sc

Final

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Provide the screenshot of accuracy of metrics you implemented @Mochoye

**Comment by Mochoye** [comment]
> Provide the screenshot of accuracy of metrics: MSE, MAE and RMSE you implemented @Mochoye

Updated

**Comment by Rakesh9100** [comment]
Good work!! @Mochoye Congrats on getting your first PR merged to this repo under GSSoC23 🎉Keep Contributing.

**Comment by Mochoye** [comment]
Finally :-) Thank You♥

**Pull request merged**
