### PR TITLE
Results images updated

### LINKED ISSUE #135: Update results screenshots in Readme file
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I would like to update readme file with the latest screenshots of results.

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by Juhibhojani**
# Fixes Issue🛠️

Closes #135 

# Description👨‍💻 

I was unable to run all algorithms and hence, have just updated linear regression plots and metrics for all algorithms. I have updated the readme file as well. I don't expect any points for this.  

# Type of change📄

Adding screenshot results.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Linear regression screenshots are already present. Pls don't change the URLs of Linear Regression. Keep as it was @Juhibhojani

**Comment by Juhibhojani** [comment]
Done @Rakesh9100

**Comment by Rakesh9100** [comment]
There are not enough screenshots as per discussed on the issue, still providing Level 1 points @Juhibhojani

**Comment by Rakesh9100** [comment]
Pls attach the screenshots in the description above below Screenshots/GIF @Juhibhojani

**Comment by Rakesh9100** [comment]
The screenshots are not enough as many more models are implemented and their plots and graphs screenshots are missing but still rewarding with level 1 @Juhibhojani 🎉

**Pull request merged**
