### PR TITLE
Added other data visualization plots

### LINKED ISSUE #92: Add other data visualization plots
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

@Rakesh9100 Respected Sir,

I want to add more visual plots for the data points of the dataset.
Please kindly assign this issue to me.

Thank you

Regards
Dhruv Saxena

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by dhruvsaxena11**
# Fixes Issue🛠️

Closes #92 

# Description👨‍💻 
Respected Sir @Rakesh9100,

I have added the scatter and histogram plots of multiple features of training dataset and also added the separate histogram for drug name.

Plz kindly check.

Thank You

Dhruv Saxena
# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I have tested it in separate notebook

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
image
image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls give the title and axes names for the second graph. Also after making your changes run `black main.py` on your editor and then make the commit.

**Comment by Rakesh9100** [comment]
Pls give the title for both the graphs and axes names for the second graph.
Also after making your changes run `black main.py` on your editor and then make the commit. @dhruvsaxena11

**Comment by dhruvsaxena11** [comment]
@Rakesh9100 Respected Sir,

Please Kindly check I updated the code.

Thank You

**Comment by Rakesh9100** [comment]
Pls provide the updated graphs screenshots @dhruvsaxena11

**Comment by dhruvsaxena11** [comment]
@Rakesh9100 Plz find the screenshots.

image

image

**Comment by Rakesh9100** [comment]
LGTM!! Merged 🎉

**Pull request merged**
