### PR TITLE
Added the Data Preprocessing and EDA part

### PR DESCRIPTION
**Pull request by HarshAggarwal1**
# Fixes Issue🛠️

Closes #

# Description👨‍💻 

# Type of change📄

- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls don't change tsv to csv file. Work on the provided dataset.
Don't change the path of the file.

**Comment by HarshAggarwal1** [comment]
Hi, I haven't changed the file type from tsv to csv, and I done everything in main.py, no files are changed now. Sorry I have forgot to delete one folder, I will remove it now.

**Comment by Rakesh9100** [comment]
Do check this <https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/pull/71/files>. The csv files are added and path of the file is showing of your PC.

**Comment by HarshAggarwal1** [comment]
Oh sorry I missed it. I am correcting it now.

**Comment by HarshAggarwal1** [comment]
I have corrected it now, Please check

**Pull request closed without merging**
