### PR TITLE
Implemented Deep Learning Algorithms

### PR DESCRIPTION
**Pull request by SRINIVAS-2003**
I have implemented ANN and AdaBoost algorithms and plotted some graphs like accuracy plot , predicted VS testing and training data values for the above two algorithms. A confusion matrix of the above two algorithms is also performed.

### CODE REVIEW

**Comment by Rakesh9100** [comment]
As you have created PR you might have got an automatic template, so pls follow that and update the description accordingly.
For reference see this, https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/PULL_REQUEST_TEMPLATE.md

Update the PR title similar to the work you have done.
@SRINIVAS-2003

**Comment by Rakesh9100** [comment]
As you have created PR you might have got an automatic template, so pls follow that and edit and update the description accordingly.
For reference see this, https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/PULL_REQUEST_TEMPLATE.md

Update the PR title similar to the work you have done.
@SRINIVAS-2003

**Comment by SRINIVAS-2003** [comment]
# Fixes Issue🛠️



Issue Number #50
Deep Learning Algorithms performed to improve the accuracy

# Description👨‍💻 


I have implemented ANN and AdaBoost algorithms and plotted some graphs like accuracy plot , predicted VS testing and training data values for the above two algorithms. A confusion matrix of the above two algorithms is also performed.

# Type of change📄



- [] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)

# How this has been tested✅


I have tested accuracy using ANN and AdaBoost algorithms.
Mainly I have used Google tool (Google Colab) to run and test the project whether the code is working or not.

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added demonstration in the form of GIF/video file
- [] I am an Open Source Contributor

# Screenshots/GIF📷
Screenshot (210)
Screenshot (211)
Screenshot (212)
Screenshot (213)
Screenshot (214)
Screenshot (215)
Screenshot (216)
Screenshot (217)
Screenshot (218)
Screenshot (219)

**Comment by Rakesh9100** [comment]
Mention the issue number this PR closes.
Provide the screenshots of the accuracies obtained and also of the plots.
Update the PR title similar to the work you have done @SRINIVAS-2003

**Comment by SRINIVAS-2003** [comment]
@Rakesh9100 
I have updated the required changes which u mentioned above.
Still, any changes required please kindly suggest me.

**Comment by Rakesh9100** [comment]
Pls run `black main.py` on your terminal in the project directory and then commit the new changes to pass the linting check @SRINIVAS-2003

**Comment by SRINIVAS-2003** [comment]
how to do that black main.py ?
Can u please guide me @Rakesh9100

**Comment by Rakesh9100** [comment]
Can you pls tell me that are you using GitHub Desktop or Git or any code editor for pushing and commiting the changes?

**Comment by SRINIVAS-2003** [comment]
I'm having github desktop , but I am having no idea how to push code

**Comment by Rakesh9100** [comment]
You must have the folder of the clone of this forked repo on your local system in which you made these code changes. Open that using Visual Studio Code. Open a new terminal and run `black main.py`. For further issues pls DM me on discord.

**Comment by SRINIVAS-2003** [comment]
@Rakesh9100 
I have done the above procedure using VS CODE and Github desktop.
I have made new pull request.
Please once check

**Pull request closed without merging**
