### PR TITLE
Changed Plot Confusion Matrix to ConfusionMatrixDisplay and added Requirements.txt file

### LINKED ISSUE #23: Add Requirements.txt file
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

To maintain a python project we need to create a requirements file to avoid dependency conflicts in the future..
I will create a virtual environment for this project and create a requirements.txt file which can be installed by :
```$ pip install -r requirements.txt```

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### LINKED ISSUE #24: Change Plot Confusion Matrix to ConfusionMatrixDisplay
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

the method ```plot_confusion_matrix``` from ```sklearn.metrics``` has been _deprecated since scikit-learn version 1.0_.
Either use an older version of  sklearn and specify it in the requirements.txt file or use the method ```ConfusionMatrixDisplay``` from ```sklearn.metrics``` 
Documentation link : https://scikit-learn.org/stable/modules/generated/sklearn.metrics.ConfusionMatrixDisplay.html#sklearn-metrics-confusionmatrixdisplay

### Screenshots

image

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by Grogu22**
# Fixes Issue🛠️

Closes #23 

Closes #24 

# Description👨‍💻 

For #23  : I created a dependencies file using `pip`
For #24 : I replaced the `plot_confusion_matrix` method from `sklearn.metrics` by `ConfusionMatrixDisplay`

# Type of change📄

- [x] Bug fix (non-breaking change which fixes an issue)

# How this has been tested✅

Converted the features to type `str` to avoid `TypeError`

```
X_train.columns = X_train.columns.astype(str)
X_test.columns = X_test.columns.astype(str)
```
Ran the code in a virtual environment, running perfectly fine with no errors

Appended the dependencies in the virtual environment to the `requirements.txt` file

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

**Fig:** the `requirements.txt` file

Programming running normally
Figure_1
**Fig :** Plotting Confusion Matrix for _Logistic Regression classifier_
Figure_2
**Fig :**  Plotting Confusion Matrix for _Decision Tree classifier_

### CODE REVIEW

**Comment by Grogu22** [comment]
@Rakesh9100 ?

**Comment by Rakesh9100** [comment]
Pls resolve the conflict @Grogu22

**Comment by Grogu22** [comment]
done @Rakesh9100

**Comment by Rakesh9100** [comment]
Good work!! @Grogu22 Congrats on getting your first PR merged to this repo under GSSoC23 🎉Keep Contributing.

**Pull request merged**
