### PR TITLE
Added SVM and Random Forest Model

### PR DESCRIPTION
**Pull request by sijalalyy**
I have applied SVM and Random Forest Model

# Fixes Issue🛠️

issue # 10

# Description👨‍💻 
I have added SVM and RF ML models to improve accuracy

# Checklist✅ 

- [] My code follows the style guidelines of this project
- [] I have performed a self-review of my own code
- [] I have commented my code, particularly in hard-to-understand areas
- [] I am an Open Source GSSOC'23 Contributor

### CODE REVIEW

**Comment by sijalalyy** [comment]
Issue # 10 complete

**Comment by Rakesh9100** [comment]
Where is the code for accuracies of both the models and how much accuracy or MSE you got? @sijalalyy

**Comment by Rakesh9100** [comment]
Closing for having no response.

**Comment by Rakesh9100** [comment]
Closing for having no response

**Pull request closed without merging**
