### PR TITLE
Added scatter visualization of drug name and ratings

### LINKED ISSUE #51: Add scatter visualization of drug name and ratings
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

@Rakesh9100 Dear Sir,

I am an GSSOC 2023 open source contributor and Data Science enthusiast. I will be creating multiple plot charts for data visualization and accuracy metrics visualization of the data set.

Please kindly assign me this task and It will be a great opportunity for me to work on it.

Thank you

Dhruv Saxena

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by dhruvsaxena11**
# Fixes Issue🛠️

Closes #51 

# Description👨‍💻 

*Actually I am currently working on my this issue so not closing it at the time.*

I recently added the scatter plot between drug name and ratings for its scatter visualization.

# Type of change📄

- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

I created this in my new notebook by fetching the dataset and doing its processing and plotting and added it in the codebase.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷

image

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Pls pull the latest code changes and resolve the conflicts @dhruvsaxena11 
Also don't change the path of dataset and name of its variable

**Comment by dhruvsaxena11** [comment]
Respected Sir @Rakesh9100 ,
I updated the repo and do some changes in variable names and dataset name.
Plz kindly check.

Thank You

Dhruv Saxena

**Comment by Rakesh9100** [comment]
image

Pls remove these repetitive LOCs as already present @dhruvsaxena11

**Review by dhruvsaxena11 — COMMENTED** [review]
@Rakesh9100 

Respected Sir,

Please Kindly check I have updated it.

Thank You

Dhruv Saxena

**Comment by Rakesh9100** [comment]
Congrats on getting your PR merged under GSSoC23 @dhruvsaxena11 🎉

**Pull request merged**
