### PR TITLE
Added the Arima model

### PR DESCRIPTION
**Pull request by ayushrathore111**
fixed issue #83 

# Implemented the model: Arima Forecasting

# Description👨‍💻 
I have added the Arima forecasting model and the errors values are:
 r2 value of testing data is : -8.314385300778326e-05
 mean squared error: 10.792894564836246
and added the plots of scatter between the actual vs predicted.

# Type of change📄

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How this has been tested✅

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added demonstration in the form of GIF/video file
- [x] I am an Open Source Contributor

# Screenshots/GIF📷
here are images of results and plots of arima :

Screenshot (257)
ml contributions 2
ml contributions3
ml_contributions1

### CODE REVIEW

**Comment by Rakesh9100** [comment]
Resolve the conflicts and keep the `main.py` file only @ayushrathore111

**Comment by ayushrathore111** [comment]
@Rakesh9100 conflicts resolved!!

**Comment by Rakesh9100** [comment]
Why there are 22 files? @ayushrathore111

**Comment by ayushrathore111** [comment]
@Rakesh9100 sir these are files actually in history folder in vs code and there is only one main file main.py in which I added the code...

**Comment by Rakesh9100** [comment]
Do remove the history folder then and keep only the main file @ayushrathore111

**Comment by ayushrathore111** [comment]
@Rakesh9100 deleted the .history directory

**Comment by Rakesh9100** [comment]
image

Why these are repeated? Delete these LOCs @ayushrathore111

**Comment by ayushrathore111** [comment]
@Rakesh9100 sir these are not repeated part. it is the part which is conflicts due to with my code that's why I just changed the spacing of that code so that the conflicts could be removed...

**Comment by Rakesh9100** [comment]
Conflicts should be resolved in such a way that only your code addition should be visible in this PR @ayushrathore111

**Comment by ayushrathore111** [comment]
but sir conflict was showing in that code also that's why 🥲🥲

**Comment by Rakesh9100** [comment]
You can close this PR and then create a new PR. First pull the latest changes if there are in the repository, make your changes, and also run `black main.py` to pass the lint workflow and then commit to the new PR @ayushrathore111

**Pull request closed without merging**
