### PR TITLE
Added Categorical and heat plot graph

### PR DESCRIPTION
**Pull request by Abhinavcode13**
# Fixes Issue🛠️(#15 )

closes the issue #15 

# Description👨‍💻 

I have added the categorical and matrix (heat plot) graph under the seaborn library.

# Type of change📄

- [✔️ ] New feature (non-breaking change which adds functionality)

# Checklist✅ 

- [✔️ ] My code follows the style guidelines of this project
- [✔️ ] I have performed a self-review of my own code
- [✔️ ] I have commented my code, particularly in hard-to-understand areas
- [✔️ ] I have added demonstration in the form of GIF/video file
- [✔️ ] I am an Open Source Contributor

### CODE REVIEW

**Comment by Abhinavcode13** [comment]
please check this @Rakesh9100

**Comment by Rakesh9100** [comment]
Provide the screenshot of the output @Abhinavcode13

**Comment by Abhinavcode13** [comment]
how can I run this main.py @Rakesh9100

**Comment by karthikbhandary2** [comment]
using the command `python main.py` or if you are using vs code you can simply click the run button at the top right corner @Abhinavcode13

**Comment by Abhinavcode13** [comment]
hey @Rakesh9100 
image
can you help me out with this

**Comment by karthikbhandary2** [comment]
@Abhinavcode13 do you have them installed on your device? Why don't you pip-install them once and see if they are present?

**Comment by Rakesh9100** [comment]
Pull the latest changes and run `pip install requirements.txt`. @Abhinavcode13

**Comment by Abhinavcode13** [comment]
image
please help me out @Rakesh9100

**Comment by karthikbhandary2** [comment]
@Abhinavcode13 plot_confusion_matrix has been deprecated. You cannot use it. I think it's best for you to pull the latest changes done on the repo which has solved this error.

**Comment by Abhinavcode13** [comment]
bro i cant run my code im trying really hard :(

**Comment by Abhinavcode13** [comment]
How can you run on google colab? @karthikbhandary2

**Comment by karthikbhandary2** [comment]
Just copy the whole code and paste it in the colab notebook

**Comment by Abhinavcode13** [comment]
how to add dataset in it?

**Comment by karthikbhandary2** [comment]
I used URLs to add the data.
```
train_url = 'https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/raw/main/datasets/drugsComTrain_raw.tsv'
test_url = 'https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/raw/main/datasets/drugsComTest_raw.tsv'

dtypes = { 'Unnamed: 0': 'int32', 'drugName': 'category', 'condition': 'category', 'review': 'category', 'rating': 'float16', 'date': 'string', 'usefulCount': 'int16' }
train_df = pd.read_csv(train_url, sep='\t', quoting=2, dtype=dtypes, parse_dates=['date'])

train_df = train_df.sample(frac=0.5, random_state=42)
test_df = pd.read_csv(test_url, sep='\t', quoting=2, dtype=dtypes, parse_dates=['date'])
```

**Comment by Rakesh9100** [comment]
Closing this as no response for many days

**Pull request closed without merging**
