### PR TITLE
Added XGBClassifier Model and WordCloud for the Review Column

### LINKED ISSUE #8: Add XGBClassifier Model and WordCloud for the Review Column
### Prerequisites

- [X] I am an Open Source Contributor
- [X] I checked to make sure that this issue has not already been filed

### Description

I'm a GSSoC'23 contributor. I would like to work on this ML-project to modify its model using Text Classification techniques as well as constructing Hybrid models.

### Screenshots

_No response_

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rakesh9100/ML-Project-Drug-Review-Dataset/blob/main/.github/CONTRIBUTING_GUIDELINES.md) of this project.

### PR DESCRIPTION
**Pull request by sahaycodes**
Close #8 

# Description👨‍💻 

In this PR , I have done the following things as follows:-
1.Data Cleaning , EDA.
2. Text Pre-Processing
3. Created WordCloud
4. Text Classification / Feature Extraction (Bag of Words -BoW)
5.  Model Building (XGBClassifier)
6. Generated Graphs for the relations.

# Type of change📄

- Cleaned the data and applied the concepts of Text Pre-Processing
like
- New feature :- Created Word Cloud for the 'review' column for ratings >=5 and <=5 
- Text Classification was done by Feature Extraction using BoW on the reviews column 
- New feature:- Using BoW and ratings , splitted the dataset in training and testing for The XGBClassifier 
- Noted down the precision and accuracy score for the same 
-  Created Graph of Accuracy Score & Precision Score 
-  Created Scatter Plot for - Predicted Values and Actual Values (Testing Data)

- # How this has been tested✅

Ran the thing in Jupyter Notebook and verified it - by the successful creation of WordClouds , Graphs and Scatter Plot.

# Checklist✅ 

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [X] I have added demonstration in the form of GIF/video file
- [X] I am an Open Source Contributor

# Screenshots/GIF📷
 Updated SS of WordClouds and XGBoost Model's Findings.
Word Cloud >=5 rating and <=5 rating
Screenshot (61)

Graph for the Model & Scatter Plot for the Model
Screenshot (62)

### CODE REVIEW

**Comment by sahaycodes** [comment]
Can someone please review this PR. Waiting for a reponse

**Comment by Rakesh9100** [comment]
Why to create a seperate file? You can continue your code in `main.py` with your model addition taking rating as the target variable. @sahaycodes

**Comment by sahaycodes** [comment]
Okay will do that

**Comment by sahaycodes** [comment]
@Rakesh9100 ...have updated PR as per your comments . Kindly review the code.

**Comment by Rakesh9100** [comment]
image

This is already done in the code above and you have repeated the same line. May I know why? @sahaycodes

**Comment by sahaycodes** [comment]
I was just double checking it , I will delete it if needed.

**Comment by Rakesh9100** [comment]
Pls keep the necessary lines of codes and also do provide the output screenshot again after proper running it.

**Comment by sahaycodes** [comment]
Okay will do that.

**Comment by sahaycodes** [comment]
Have updated the PR- with appropriate code and screenshot of the findings.

**Comment by Rakesh9100** [comment]
LGTM!! Congrats on getting your PR merged to this repo under GSSoC23 🎉 @sahaycodes

**Comment by sahaycodes** [comment]
Thankyou for this opportunity @Rakesh9100 :)

**Pull request merged**
